version: '3.8'

services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-prod
    restart: unless-stopped
    stop_grace_period: 60s
    
    env_file:
      - .env.production
    
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python.*bot.py' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    volumes:
      - ./data/logs:/app/logs:rw
      - ./data/backups:/app/backups:rw
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'